const mockRobots = [
  {
    id: "RBT-001",
    name: "Alpha-01",
    status: "active",
    battery: 92,
    task: "Patrolling Zone A",
    uptime: 7200,
    location: { lat: 28.6139, lng: 77.2090, label: "Warehouse Delhi-A" },
    errorLog: [],
    lastPing: "2 mins ago",
  },
  {
    id: "RBT-002",
    name: "Beta-02",
    status: "working",
    battery: 74,
    task: "Sorting packages",
    uptime: 5400,
    location: { lat: 28.6219, lng: 77.2195, label: "Warehouse Delhi-B" },
    errorLog: [],
    lastPing: "1 min ago",
  },
  {
    id: "RBT-003",
    name: "Gamma-03",
    status: "error",
    battery: 31,
    task: "Idle — motor fault",
    uptime: 1200,
    location: { lat: 28.6050, lng: 77.2250, label: "Floor 2 Delhi" },
    errorLog: ["Motor overheat at 14:02", "Restart failed at 14:05"],
    lastPing: "8 mins ago",
  },
  {
    id: "RBT-004",
    name: "Delta-04",
    status: "idle",
    battery: 100,
    task: "Awaiting task",
    uptime: 0,
    location: { lat: 28.6300, lng: 77.2150, label: "Charging Bay" },
    errorLog: [],
    lastPing: "5 mins ago",
  },
  {
    id: "RBT-005",
    name: "Epsilon-05",
    status: "active",
    battery: 85,
    task: "Delivery Route C",
    uptime: 3600,
    location: { lat: 28.6180, lng: 77.2040, label: "Corridor East" },
    errorLog: [],
    lastPing: "just now",
  },
  {
    id: "RBT-006",
    name: "Zeta-06",
    status: "working",
    battery: 60,
    task: "Assembling Unit 9",
    uptime: 9000,
    location: { lat: 28.6080, lng: 77.2310, label: "Assembly Line 3" },
    errorLog: [],
    lastPing: "3 mins ago",
  },
  {
    id: "RBT-007",
    name: "Eta-07",
    status: "error",
    battery: 12,
    task: "Stuck — sensor failure",
    uptime: 300,
    location: { lat: 28.6250, lng: 77.1990, label: "Loading Dock" },
    errorLog: ["Lidar sensor offline at 09:45"],
    lastPing: "15 mins ago",
  },
  {
    id: "RBT-008",
    name: "Theta-08",
    status: "idle",
    battery: 98,
    task: "Standby",
    uptime: 0,
    location: { lat: 28.6110, lng: 77.2220, label: "Charging Bay 2" },
    errorLog: [],
    lastPing: "4 mins ago",
  },
  {
    id: "RBT-009",
    name: "Iota-09",
    status: "active",
    battery: 77,
    task: "Inspection Route B",
    uptime: 4800,
    location: { lat: 28.6020, lng: 77.2100, label: "Rooftop Zone" },
    errorLog: [],
    lastPing: "just now",
  },
  {
    id: "RBT-010",
    name: "Kappa-10",
    status: "working",
    battery: 55,
    task: "Inventory scan",
    uptime: 6600,
    location: { lat: 28.6160, lng: 77.2280, label: "Storage Floor B" },
    errorLog: [],
    lastPing: "2 mins ago",
  },
];

export default mockRobots;